Repository cloudfoundry-incubator/kubo-deployment, pull requests merged in 2019-03, with the labels that each got.

#358 Add opsfiles for adding a Windows worker
  bin/test-standard-ops.sh
  manifests/README.md
  manifests/ops-files/iaas/vsphere/windows/cloud-provider.yml
  manifests/ops-files/iaas/vsphere/windows/use-vm-extensions.yml
  manifests/ops-files/misc/deployment-name.yml
  manifests/ops-files/misc/version.yml
  manifests/ops-files/use-hostgw.yml
  manifests/ops-files/windows/add-worker.yml
  manifests/ops-files/windows/enable-rdp.yml
  manifests/ops-files/windows/scale-to-one-az.yml
  manifests/ops-files/windows/use-hostgw.yml
  manifests/ops-files/windows/vm-types.yml
Labels: scheduled

#384 Set the root-dir to a partition that is scalable
  manifests/cfcr.yml
Labels: unscheduled

#382 Add opsfile to up fs.inotify limit to allow more file watchers
  bin/test-standard-ops.sh
  manifests/README.md
  manifests/ops-files/example-vars-files/fs-inotify-limit.yml
  manifests/ops-files/set-fs-inotify-limit.yml
Labels: unscheduled

#383 Template bbr.backup_one_restore_all property for bbr-etcd job
  manifests/ops-files/enable-bbr.yml
Labels: unscheduled

#385 Update Windows workers to use 2019 stemcells
  manifests/ops-files/windows/add-worker.yml
Labels: in progress

#387 Update windows/add-worker.yml to fetch external windows release
  manifests/ops-files/windows/add-worker.yml
Labels: unscheduled
